apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" .}}-service
  labels:
    app: {{ include "fullname" .}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ include "fullname" .}}
